# Generated by Django 3.2.14 on 2022-07-06 11:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_postupdateregister'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='postUpdateRegister',
            new_name='PostUpdate',
        ),
    ]
