# Generated by Django 3.2.14 on 2022-07-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_related_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='related_posts',
        ),
        migrations.AddField(
            model_name='post',
            name='related_posts',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='_blog_post_related_posts_+', to='blog.Post'),
        ),
    ]
