# Generated by Django 3.2.14 on 2022-07-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220711_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='related_posts',
            field=models.ManyToManyField(blank=True, default=None, related_name='_blog_post_related_posts_+', to='blog.Post'),
        ),
    ]
