# Generated by Django 3.2.14 on 2022-07-11 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_comments_post_commentsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commentSection',
        ),
        migrations.AddField(
            model_name='commenttree',
            name='post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
